//
//  ItemPropertiesPanel.swift
//  TierSpec
//
//  Created by Sisyphus on 2026/5/1.
//

import SwiftUI

struct ItemPropertiesPanel: View {
    let item: TierItemDTO
    @ObservedObject var treeStore: TreeStore
    
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                metadataSection
                
                Divider()
                
                statisticsSection
                
                if item.sprintId != nil {
                    Divider()
                    sprintSection
                }
                
                if item.aiGenerated {
                    Divider()
                    aiMetadataSection
                }
                
                Divider()
                
                stateTransitionsSection
            }
            .padding()
        }
        .navigationTitle("Properties")
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
    }
    
    private var metadataSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            SectionHeader(title: "Metadata", icon: "info.circle")
            
            PropertyRow(label: "ID", value: item.id.uuidString.prefix(8))
            PropertyRow(label: "Type", value: item.type.displayName)
            PropertyRow(label: "Created", value: item.createdAt.formatted(date: .abbreviated, time: .shortened))
            PropertyRow(label: "Updated", value: item.updatedAt.formatted(date: .abbreviated, time: .shortened))
            
            if let deletedAt = item.deletedAt {
                PropertyRow(label: "Deleted", value: deletedAt.formatted(date: .abbreviated, time: .shortened))
            }
        }
    }
    
    private var statisticsSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            SectionHeader(title: "Statistics", icon: "chart.bar")
            
            PropertyRow(label: "Children", value: "\(item.children.filter { $0.deletedAt == nil }.count)")
            PropertyRow(label: "Position", value: String(format: "%.1f", item.position))
            
            if let storyPoints = item.storyPoints {
                PropertyRow(label: "Story Points", value: "\(storyPoints)")
            }
            
            if let complexity = item.complexity {
                HStack {
                    Text("Complexity")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Spacer()
                    Text(complexity.displayName)
                        .font(.caption)
                        .fontWeight(.medium)
                        .foregroundStyle(complexity.color)
                        .padding(.horizontal, 8)
                        .padding(.vertical, 4)
                        .background(complexity.color.opacity(0.1), in: Capsule())
                }
            }
        }
    }
    
    private var sprintSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            SectionHeader(title: "Sprint", icon: "calendar")
            
            if let sprintId = item.sprintId {
                PropertyRow(label: "Sprint ID", value: sprintId.uuidString.prefix(8))
            } else {
                Text("Not assigned to sprint")
                    .font(.caption)
                    .foregroundStyle(.tertiary)
            }
        }
    }
    
    private var aiMetadataSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            SectionHeader(title: "AI Generation", icon: "sparkles")
            
            if let confidence = item.aiConfidence {
                HStack {
                    Text("Confidence")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Spacer()
                    ConfidenceBadge(confidence: confidence)
                }
            } else {
                HStack {
                    Text("Generated by AI")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Spacer()
                    Image(systemName: "checkmark.circle.fill")
                        .foregroundStyle(.purple)
                        .font(.caption)
                }
            }
            
            if let reasoning = item.aiReasoning, !reasoning.isEmpty {
                ReasoningPanel.Inline(reasoning: reasoning, confidence: item.aiConfidence)
            }
        }
    }
    
    private var stateTransitionsSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            SectionHeader(title: "State Transitions", icon: "arrow.triangle.branch")
            
            VStack(alignment: .leading, spacing: 8) {
                HStack {
                    Text("Current Status")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Spacer()
                    HStack(spacing: 4) {
                        Circle()
                            .fill(item.status.color)
                            .frame(width: 8, height: 8)
                        Text(item.status.displayName)
                            .font(.caption)
                            .fontWeight(.medium)
                    }
                }
                
                if item.status.isTerminal {
                    Text("Terminal state - no further transitions")
                        .font(.caption2)
                        .foregroundStyle(.tertiary)
                        .padding(.vertical, 4)
                } else {
                    Text("Available transitions depend on actor type and current state")
                        .font(.caption2)
                        .foregroundStyle(.tertiary)
                        .padding(.vertical, 4)
                }
            }
        }
    }
}

struct SectionHeader: View {
    let title: String
    let icon: String
    
    var body: some View {
        HStack(spacing: 6) {
            Image(systemName: icon)
                .font(.caption)
                .foregroundStyle(.secondary)
            Text(title)
                .font(.caption)
                .fontWeight(.semibold)
                .foregroundStyle(.secondary)
                .textCase(.uppercase)
        }
    }
}

struct PropertyRow: View {
    let label: String
    let value: any StringProtocol
    
    var body: some View {
        HStack {
            Text(label)
                .font(.caption)
                .foregroundStyle(.secondary)
            Spacer()
            Text(String(value))
                .font(.caption)
                .fontWeight(.medium)
                .foregroundStyle(.primary)
        }
    }
}

#Preview {
    ItemPropertiesPanel(
        item: TierItemDTO(
            id: UUID(),
            type: .userStory,
            parentId: UUID(),
            sprintId: UUID(),
            title: "Sample Story",
            description: "A sample story for preview",
            status: .inProgress,
            priority: 50,
            position: 1.0,
            storyPoints: 5,
            complexity: .m,
            aiGenerated: true,
            aiConfidence: 0.85,
            aiReasoning: "This story was generated based on the feature requirements and follows the standard user story format.",
            labels: ["frontend", "ui"],
            createdAt: Date().addingTimeInterval(-86400 * 7),
            updatedAt: Date().addingTimeInterval(-3600),
            deletedAt: nil,
            children: []
        ),
        treeStore: TreeStore(mcpClient: MCPToolClient(clientManager: MCPClientManager()))
    )
    .frame(width: 320)
}
